---
title: Entity Relationship Diagram Back-end Project
---
erDiagram
    Cliente {
      id_cliente int
      user varchar
      email varchar
      senha varchar
      telefone varchar
      id_admin int
    }

    Funcionario {
      id_funcionario int
      user varchar
      email varchar
      senha varchar
      cargo varchar
      salario decimal
      id_admin int
    }

    Admin {
      id_admin int
      user varchar
      email varchar
      senha varchar
    }

    Produto {
      id_produto int
      nome varchar
      descricao text
      preco decimal
      quantidade int
      categoria varchar
    }

    Pedido {
      id_pedido int
      id_cliente int
      data date
      status varchar
      total decimal
    }

    ProdutoSelecionado {
      id_prod_selec int
      id_pedido int
      id_produto int
      quantidade int
      preco_unitario decimal
    }

    Cliente ||--o{ Pedido : "Realiza"
    Funcionario ||--o{ Pedido : "Registra"
    Pedido }|--o{ ProdutoSelecionado : "Contém"
    Produto }|--o{ ProdutoSelecionado : "Contém"
    Admin ||..|{ Funcionario : "Gerencia"
    Admin ||..|{ Cliente : "Gerencia"
